package ohim:dom;

interface node {
    resource node {
        append-child: func(child: node) -> node;
    }

    resource document {
        constructor();
        url: func() -> string;
        document-element: func() -> option<element>;
    }

    resource element {
        has-attributes: func() -> bool;
    }
}
